name: IETF Trac Archiver

on:
  workflow_dispatch:
  
jobs:
  scrape-trac:
    name: Scrape trac.ietf.org
    runs-on: ubuntu-latest
    steps:
    - name: wget pages
      run: |
        wget --recursive --page-requisites --adjust-extension \
             --convert-links --restrict-file-names=windows  \
             --domains trac.ietf.org --no-parent \
             https://trac.ietf.org/trac/wgchairs || true
        tar czvf trac.ietf.org.tgz trac.ietf.org
  
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trac_archive
        path: trac.ietf.org.tgz
